# Generated by Django 4.0.4 on 2022-06-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('-status',)},
        ),
        migrations.AddField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
